# Generated by Django 2.0 on 2020-08-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('dept', models.SmallIntegerField()),
                ('long', models.SmallIntegerField()),
                ('lat', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'city',
                'ordering': ['dept', 'name'],
            },
        ),
    ]
