# Generated by Django 2.0 on 2020-08-24 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_market', '0002_market'),
    ]

    operations = [
        migrations.CreateModel(
            name='NbFarmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale', models.CharField(max_length=5)),
                ('icon', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'farmer',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='market',
            name='nb_farmers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farmer_market.NbFarmer'),
        ),
    ]
