# Generated by Django 2.0 on 2020-08-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_market', '0003_auto_20200824_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='market',
            name='long',
            field=models.FloatField(),
        ),
    ]
