# Generated by Django 2.0 on 2020-08-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_market', '0004_auto_20200824_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='city',
            name='long',
            field=models.FloatField(),
        ),
    ]
